### ISSUE TITLE
Support inline images

### ISSUE THREAD

**Issue by kl1703222** [meliorence/react-native-render-html#428]
I want to display the icon in the middle of the text, for example below:
<img width="340" alt="a" src="https://user-images.githubusercontent.com/58561076/98535085-1a917800-22b8-11eb-92ad-6d143fc6d0eb.png">
but in my mobile device using <HTML /> it displays the wrong size and not in the same line:
<img width="406" alt="Screen Shot 2020-11-09 at 18 20 48" src="https://user-images.githubusercontent.com/58561076/98535272-65ab8b00-22b8-11eb-8f51-de69854d77d3.png">
my code:
 ```
 <HTML
            html={`<p>An inline SVG image is embedded to present the Italy flag
<img src="https://fomoyolo-dev-assets.s3.amazonaws.com/image-gallery/c4ea7600-9acb-11ea-a7d0-9bf50f73b3c4.jpg" style="height:px; width:10px" />
in a paragraph of text...
</p>`}/>
```
How can I display images between lines of text?

**Comment by jsamr** [comment]
@kl1703222 Currently, inline images are not supported. Any embedded or block will be hoisted to a new View and break the text flow. This was originally because RN didn't support nesting Views inside Text nodes. It is now *possible*, but with some limitations and prone to bugs. We might add a way in a forthcoming release to whitelist tags which can be embedded in Text nodes.

Known issues regarding inline contents so far:

- Density issue with images on Android: https://github.com/facebook/react-native/issues/11906
- Images cropped: https://github.com/facebook/react-native/issues/29559
- Reconciliation bug: https://github.com/facebook/react-native/issues/29665

My feeling is that, theoretically RN now supports nested Views and other blocks inside Text, but there are probably still a lot of undiscovered issues.

**Comment by jsamr** [comment]
This feature is available in the Foundry release! Try it out now. Check #430 for instructions. There is a specific example available in the Foundry Playground app, "Model tampering". Just check the source code in the Foundry Playground for an example. Below is the result: 

![Screenshot_1606412178](https://user-images.githubusercontent.com/3646758/100380125-f2fb1900-2ff4-11eb-8bd3-fa5cd5422825.png)

**Comment by jsamr** [comment]
Closing now since the stable beta which fixes this issue [has just been released](https://github.com/meliorence/react-native-render-html/releases/tag/v6.0.0-beta.0).
