### ISSUE TITLE
<img> tags do not render their image content on 6.0.0-alpha.12

### ISSUE THREAD

**Issue by dstaley** [meliorence/react-native-render-html#460]
### Oath

I swear that I have completed these tasks before submitting:

- [x] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [x] I have read the documentation here: https://git.io/JJcAl 
- [x] I have confirmed that this bug has not been reported yet

### Decision table

- [x] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless
  we claim support for it),
- [x] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Bug Report

The content of images is not rendered. A View is created for them (including a border and alt text if provided), but the actual image content is not rendered.

#### Devices

- Samsung Galaxy S21
  * OS: Android 11
  * Diagnostic: 
  * Environment: development

##### Description

1. Render HTML containing an `<img>` tag with a valid `src` attribute

Expected result: Image is rendered
Actual result: An empty box is rendered

##### Reproducible Demo

[Snack](https://snack.expo.io/@dstaley/react-native-render-html-v12-img)

### Additional Notes

This issue does not occur using `v6.0.0-alpha.11`, only `6.0.0-alpha.12`.

**Comment by jsamr** [comment]
@dstaley I've marked this bug as upstream because alpha.12 is using the `URL` constructor described by [the WHATWG standard](https://url.spec.whatwg.org/), which react-native JavaScript engine doesn't follow closely, see https://github.com/facebook/react-native/issues/30914. This is why the bug does not occur on react-native-web.

I'm going to publish a patch today, probably depending on a more reliable third-party.
