### ISSUE TITLE
web page from url is not loading css and angular web sites are also not getting loaed

### ISSUE THREAD

**Issue by xXCHINNAXx** [meliorence/react-native-render-html#466]
### Oath

I swear that I have completed these tasks before submitting:

- [x] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [x] I have read the documentation here: https://git.io/JJcAl 
- [x] I have checked that the feature request has not been offered yet

### Decision table

- [x] The change I am requesting does not concern performance
- [x] The change I am requesting does not concern security
- [x] The change I am requesting does not concern code style
- [x] The change I am requesting does not concern development tooling and
  packaging and other “meta” features
- [x] The change I am requesting does not concern third-party deprecations  

### Feature

loading complete web page from remote url like https://google.com and add onLoad and refresh options if a remote url is given 
(Describe the feature here.)
in brief implement react native web view, so we can use one package to render html and the remote web link.

**Comment by jsamr** [comment]
@xXCHINNAXx This library has no pretension to replace `react-native-webview`. The two libraries fit different purposes. `react-native-render-html` bare goal is to render the HTML markup into native views. On the other hand, `react-native-webview` is a full featured embedded system web widget, shipped with a web engine of [over 2,1 millions of lines of code](https://www.openhub.net/p/v8-js), complying with a great range of standards that comprise the web today (CSS, HTML, the DOM, Web APIs, web workers, caching, security protocols, cookies...). It's understandably heavier.

I am closing because I believe this feature request stems from a misunderstanding, but you're free to continue the discussion!
