### ISSUE TITLE
Component rerenders when scrolling the page 

### ISSUE THREAD

**Issue by dennisbouwpas** [meliorence/react-native-render-html#471]
### Oath

I swear that I have completed these tasks before submitting:

- [x] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [x] I have read the documentation here: https://git.io/JJcAl 
- [x] I have confirmed that this bug has not been reported yet

### Decision table

- [x] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless
  we claim support for it),
- [x] My issue does not look like “The HTML element `<yyy>` is not rendered”

##### React Native
react-native:0.64

```

```

##### Libraries

- react-native-render-html: 5.1.0

#### Devices

- Device 1 iPhone 8 
  * OS: IOS 13.5
  * Diagnostic: negative
  * Environment: development
- Device 2 Google Pixel 4
  * OS: Android 11
  * Diagnostic: negative
  * Environment: development

##### Description

(Write your steps here:)

1. I made some custom tagsStyles

```
const tagsStyles = {
    ul: {
      paddingLeft: 0,
      marginVertical: 10,
    },
    ol: {
      paddingLeft: 0,
      marginVertical: 10,
    },
    a: {
      textDecorationLine: 'none',
      color: '#2DA343',
      margin: 0,
    },
    p: {
      margin: 0,
      paddingLeft: 0,
      paddingTop: 10,
      paddingRight: 0,
      paddingBottom: 10,
    },
    h1: {
      fontSize: 18,
      paddingRight: 60,
      color: '#2DA343',
    },
    h2: {
      fontSize: 14,
    },
  };
```

2. Then made a onParsed function to test something
3. When I scroll my page I constantly see onParsed function triggered 
4. If I remove/comment tagsStyles props, then I see onParsed only once.
5. I also have some custom renderers for h1 element (code bellow) with onLayout function to get Y coordinates of each h1 so later I can make navigation buttons and scroll to the closest element. If I do that and my page contains leet's say 20+ h1 elements, the app freezes for 5-7 seconds, and I'm not able to click anything or go back from the page. But I am able to scroll page. Can it be because its something with tagsStyles ?

```
h1: (htmlAttribs, children) => {
      let element;
      if (htmlAttribs.heading_type === '1') {
        element = (
          <View
            style={mdStyles.headingTitleWrapp}
            onLayout={(event) =>
              getLayout(event, htmlAttribs.heading_numb, {
                heading: htmlAttribs.heading_text,
                headingType: 1,
              })
            } 
          >
            <View style={mdStyles.headingTitleIndexWrapp}>
              <Text style={mdStyles.headingTitleIndexText}>{htmlAttribs.heading_numb}</Text>
            </View>

            <View style={mdStyles.headingTitleTextBlock}>
              <Text style={mdStyles.headingTitleText}>{children}</Text>
            </View>
          </View>
        );
      } else {
        <Text>{children}</Text>;
      }
      return element;
    },

```

```
<HTML
     source={{ html }}
     contentWidth={windowWidth}
     tagsStyles={tagsStyles}
     renderers={renderers}
     listsPrefixesRenderers={listsPrefixesRenderers}
     onParsed={() => {
       console.log('HTML PARSED');
     }}
  />
   ```

**Comment by jsamr** [comment]
@dennisbouwpas This is not obvious in your example, but:

- are `tagsStyles` declared in the body of your component, or is it invariant? If it is instantiated on each render, you should instead memoize it to avoid triggering re-renders.
- same goes for onParsed. I can see it is an inline arrow function, which means every render of the controlling component will trigger a re-render of the `HTML` component.
- the object in which you store the position of each `h1` element should not be part of the state, because it should never trigger re-renders. It only acts as a cache. So if by any chance you update the state `onLayout`, you should instead use a class field (for class component) or a ref via `useRef` (for functional components).

**Resources**

- [React.js → Optimizing Performance → Avoid Reconciliation](https://reactjs.org/docs/optimizing-performance.html#avoid-reconciliation)
- [React.js → Hooks → FAQ → Performance Optimizations](https://reactjs.org/docs/hooks-faq.html#performance-optimizations)

**Comment by dennisbouwpas** [comment]
@jsamr Thanks for the answer!

**Comment by jsamr** [comment]
@dennisbouwpas You're welcome!
