### ISSUE TITLE
includeFontPadding crashed at android as it convert boolean to string type "false" or "true"

### ISSUE THREAD

**Issue by sbin1211** [meliorence/react-native-render-html#485]

**Comment by jsamr** [comment]
Hi @sbin1211!
You are advised to follow [our guidelines](https://github.com/meliorence/react-native-render-html/blob/master/CONTRIBUTING.adoc#submitting-a-bug) to submit bug reports. Especially, we can't process reports which don't contain version information. If this issue happened in version 5.x, there is a good chance it has been fixed in the Foundry release, yet in alpha (see #430), which uses strict parsing of CSS properties. Feel free to update the report with at least a code snippet and version information, and we will be able to process it.
