### ISSUE TITLE
I want to use "!important" flag on some color tag but not able to do after different methods and trials also i am unable to use that.

### ISSUE THREAD

**Issue by ritwik-boringnews** [meliorence/react-native-render-html#486]
### Oath

I swear that I have completed these tasks before submitting:

- [x] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [x] I have read the documentation here: https://git.io/JJcAl 
- [x] I have checked that the feature request has not been offered yet

### Decision table

- [x] The change I am requesting does not concern performance
- [x] The change I am requesting does not concern security
- [x] The change I am requesting does not concern code style
- [x] The change I am requesting does not concern development tooling and
  packaging and other “meta” features
- [x] The change I am requesting does not concern third-party deprecations  

### Feature

(Describe the feature here.)

**Comment by jsamr** [comment]
@ritwik-boringnews Important directives are not supported, although they might in the future, and I will keep that issue open for the record. If you provide a code snippet and a use case, I might be able to help you out with tricks to get around this limitation....

**Comment by ritwik-boringnews** [comment]
Thanks sir for humble response 
The data i am getting through an api call looks like
```
"<p class=\"tbnc-default-block\">&nbsp;<span style=\"color: #00a8a8; font-weight: bold; font-size: 18px\">One-liner: </span>Board members at Microsoft made a decision in 2020 that it wasn't appropriate for its co-founder Bill Gates to continue sitting on its board as they investigated the billionaire's prior romantic relationship with a female Microsoft employee that was deemed inappropriate, according to a report in The Wall Street Journal.</p>\n<p class=\"tbnc-default-block\"><span style=\"color: #00a8a8; font-weight: bold; font-size: 18px\">Law firm hired:</span> Citing unnamed sources, The Journal reported online on Sunday that board members looking into the matter hired a law firm in late 2019 to conduct an investigation after a Microsoft engineer alleged in a letter that she had a sexual relationship with Gates over several years.</p>\n<p class=\"tbnc-default-block\"><span style=\"color: #00a8a8; font-weight: bold; font-size: 18px\">Gates quit before probe:</span> The Journal reported that Gates resigned before the board's investigation was finished, citing another person familiar with the matter.</p>\n<p class=\"tbnc-default-block\"><span style=\"color: #00a8a8; font-weight: bold; font-size: 18px\">Affair ended amicably: </span>An unnamed spokeswoman for Gates acknowledged to The Journal that there was an affair almost 20 years ago, and that it ended amicably.</p>\n<p class=\"tbnc-default-block\"><span style=\"color: #00a8a8; font-weight: bold; font-size: 18px\">Quitting not related to affair: </span>The spokesperson told The Journal that his decision to transition off the board was in no way related to this matter.</p>\n<ul>\n  <li class=\"tbnc-default-ul\">When he left Microsoft's board last year, Gates said he was stepping down to focus on philanthropy</li>\n</ul>\n<p class=\"tbnc-default-block\"><span style=\"color: #00a8a8; font-weight: bold; font-size: 18px\">Office affair:</span> In an email sent to The Associated Press late Sunday, Microsoft said that it received a concern in the latter half of 2019 that Bill Gates sought to initiate an intimate relationship with a company employee in the year 2000.</p>" 
```
and i want my classes and tags style should overlap all inline styles because i will render whole html but style should be different as per mobile screen .
I hope you understood the problem .

**Comment by jsamr** [comment]
@ritwik-boringnews You have a lot of options depending on which version you use.

## v5

- whitelist specific CSS properties via `allowedStyles` or none with an empty array (CSS properties in kebab case);
- use [`alterNode`](https://github.com/meliorence/react-native-render-html#alternode) prop to delete inline styles in the DOM. It offers you the advantage to control under which conditions to delete those.

```js
import { isTag } from "domutils";

function alterNode(node) {
  // In this example, I'm targeting only span elements.
  if (isTag(node) && node.tagName === "span") {
    delete node.attributes.style;
  }
}
```

## v6 (foundry)

see #430 

- set `enableCSSInlineProcessing` to `false` to disable all inline styles ;
- whitelist specific CSS properties via `allowedStyles` or none with an empty array (be careful, in Foundry, CSS property names should be camel cased);
- before alpha.25, use `alterDOMNode` similar to in v5 (only the prop name changed);
- since alpha.25, you need to use `domVisitors.onElement` for elements and `domVisitors.onText` for Text nodes.

**Snippet for alpha.25**
```js
const domVisitors = {
  onElement(element) {
    // In this example, I'm targeting only span elements.
    if (element.tagName === "span") {
      delete node.attributes.style;
    }
  },
};
```

**Comment by ritwik-boringnews** [comment]
sir can you help with  this types of tag
```
p::before {
  content: "Read this: ";
}
```

**Comment by jsamr** [comment]
@ritwik-boringnews Pseudo-elements are not supported yet, unfortunately ...

**Comment by ritwik-boringnews** [comment]
@jsamr no worries sir ,i just solved all the problems where i was stuck previously and thanks for the trick...pseudocode one i have solved with creating one custom element

**Comment by jsamr** [comment]
This feature will not be implemented per se, here is why: CSS sheets will never be supported, because parsing requires creating a syntax tree, which requires a third party library and would most certainly add a lot of overhead. However, we might **provide a build tool**, at some point, to convert CSS stylesheet to react-native-render-html compatible code. This tool *might* eventually support **important!** directives.
