### ISSUE TITLE
Invalid NSUnderlineStyle

### ISSUE THREAD

**Issue by mydesweb** [meliorence/react-native-render-html#496]
My HTML received from an external source contains many inline styles with invalid values. If I load the content as it is I see the following Error on iOS

![IMG_5043](https://user-images.githubusercontent.com/5901386/123002540-b2148880-d3ba-11eb-8452-1a064d55bbf1.PNG)

HTML content 
`<p style="font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 0in 0in 21.0pt 0in;"><span style="font-size: 13.0pt; color: #333333;">some text </span></p>`

please note:
text-decoration-style: **initial**;
text-decoration-color: **initial**

there is any way to ignore all inline styles received or just the ones which are not valid?

"react-native-render-html": "^5.1.1"

**Comment by jsamr** [comment]
@mydesweb V6 (`@next`) solves this issue (it has its own CSS processor which strictly validate native-translatable CSS properties); if you're not ready to [migrate](https://meliorence.github.io/react-native-render-html/docs/migration-guide), there is still the `ignoredStyles` prop at your disposal, where you can provide an array of CSS properties you wish to ignore.

Closing since similar issues have been reported many times on V5 and older versions!
