### ISSUE TITLE
I just want to render a local image, it seems it can’t

### ISSUE THREAD

**Issue by fungmo** [meliorence/react-native-render-html#499]
![image](https://user-images.githubusercontent.com/16655229/123394006-3e989400-d5d1-11eb-931e-64418da703b4.png)

**Comment by jsamr** [comment]
@fungmo Dear fungo, that will not work, because `src` attribute of img expects an URL (this is part of the HTML standard), and `require` doesn't return an URL (but rather a module identifier handled by metro). But you can use a [custom renderer](https://meliorence.github.io/react-native-render-html/docs/guides/custom-renderers#component-based-custom-rendering) for that purpose. Closing now since there won't be support for local images as such. Next time, I advise you to go to our Discord channel ;-).
