### ISSUE TITLE
Crash on android if video url is not correct

### ISSUE THREAD

**Issue by narendra87** [meliorence/react-native-render-html#504]
Steps for reproduce:

Put any incorrect video url in Html content and try to render it.
In my case incorrect url is  https://youtu.be/rP61K8-04K4?rel=0 
below is the html content:
<iframe width=\"\" height=\"\" src=\"https://youtu.be/rP61K8-04K4?rel=0\" frameborder=\"0\" allowfullscreen title=\"VACCINE TALK\"></iframe>

Thanks

**Comment by jsamr** [comment]
Dear @narendra87 
I'm closing because this issue does not follow [our contribution guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md). We are working on our free time and need a full reproduction to investigate. You are welcomed to post a new report in compliance with our guidelines.
