### ISSUE TITLE
<b>dddd</b><div><b><br></b></div>😄  the above html content showing in 5 lines

### ISSUE THREAD

**Issue by ArchanaUshaVijayan** [meliorence/react-native-render-html#512]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

```html
<b>dddd</b><div><b><br></b></div>😄 this should come as 3 lines. Its coming as 5 lines
```

### React Native Information

```sh
nothing
```

### RNRH Version

63

### Tested Platforms

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

<b>dddd</b><div><b><br></b></div>😄

**Comment by jsamr** [comment]
@ArchanaUshaVijayan This look reasonable since `div` elements will always be displayed as block elements in React Native (which only supports "flex" btw). Note that you missed some critical information in your report (React Native Render HTML version), so I assumed you used the latest. Also, you didn't provide screenshots comparing Web vs RNRH so I'm only guessing. Don't want to appear rude, I'm really willing to help but my time is limited and you are expected to do your best to provide accurate information! I'm closing now.

**Comment by ArchanaUshaVijayan** [comment]
@jsamr Sorry for the confusion and missing details in the question. Issue I am facing is in my html content I have <div><b></b></div>and a smiley. the div and b tag creating two empty line before smiley. How can I remove this empty line. Is there any way for that

**Comment by jsamr** [comment]
@ArchanaUshaVijayan You might want to clean up the HTML via dom tampering, see https://meliorence.github.io/react-native-render-html/docs/guides/dom-tampering
