### ISSUE TITLE
not render HTML like &mdash; &nbsp; etc...

### ISSUE THREAD

**Issue by ppatel31** [meliorence/react-native-render-html#525]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

not render HTML like &mdash; &nbsp; etc...

### React Native Information

```sh
not render HTML like &mdash; &nbsp; etc...
```

### RNRH Version

not render HTML like &mdash; &nbsp; etc...

### Tested Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

not render HTML like &mdash; &nbsp; etc...

### Additional Notes

not render HTML like &mdash; &nbsp; etc...

**Comment by jsamr** [comment]
Hi @ppatel31, and thank you for your submission. Unfortunately, you didn't provide mandatory fields with useful information and there is not much I can do from the little information you gave. Are you expecting to see HTML entities (`&mdash` ...etc) rendered in their UTF-8 equivalent? Or you'd like **not** to render these entities in their UTF-8 equivalent? This is not obvious from your title. Entities (`&mdash` ...etc) are decoded to UTF-8 by `htmlparser2` in the DOM parsing phase. You can chose to enable / disable entities parsing with `htmlParserOptions={{ decodeEntities: false }}` prop. This should be `true` by default. I'm closing now, but if you wish to share any extraneous information, please do.

**Comment by hanzoow** [comment]
hi @jsamr , i have content HTML like this: <div>d wq d</div><div>qw</div><div>&nbsp;d</div><div>wq d</div><div>q&nbsp;</div><div>d</div>

I want break line as html like. when i use htmlParserOptions={{ decodeEntities: false }}  prop, it show &nbsp; in UI but i dont want it to be shown. Otherwise, if i use decodeEntities: true, app crash with message is: Cannot read properties of undefined (reading '0') and track file like image below.
![image](https://user-images.githubusercontent.com/44063254/136149642-d2012644-abac-4955-876b-fc9ce0f67ccd.png)

How can i let it break line without crash ?

**Comment by jsamr** [comment]
@hanzoow please fill a bug report with a full reproduction and I'll be happy to help you out :-)
