### ISSUE TITLE
typescript compiler error because of ramda on version 6.3.4

### ISSUE THREAD

**Issue by mohameddiopcodes** [meliorence/react-native-render-html#579]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

Using version 6.3.4 to render html formatted text in react native turned out to be a problem. typescript was failing because of ramda causing our CI pipeline to reject pushed changes. 

Fix: downgraded to version 5.1.0

### React Native Information

```sh
ramda causing failure for typescript compiler.
```

### RNRH Version

6.3.4

### Tested Platforms

- [ ] Android
- [ ] iOS
- [ ] Web
- [X] MacOS
- [ ] Windows

### Reproduction Platforms

- [ ] Android
- [ ] iOS
- [ ] Web
- [X] MacOS
- [ ] Windows

### Minimal, Reproducible Example

install version 6.4.0 of the renderer on a typescript application, run the typescript compiler. Errors should pop up, Ramda is not compatible.

**Comment by jsamr** [comment]
@mohameddiopcodes you need to provide as much info as possible for us to help. At a very minimum, explain how you came up to the conclusion Ramda typings were faulty, and show the TS messages. I'm very bandwidth limited, and won't investigate issues unless they are easy to reproduce with a git/snack reproduction. Having no idea of the Typescript version used or the package manager makes it impossible to guarantee a reproduction locally.

Ramda ships no types, so the issue would eventually raise from @types/ramda, https://www.npmjs.com/package/@types/ramda
Also note that there are ways with yarn and npm to override the version used by a dependency, so that shouldn't be strictly blocking for you.

**Comment by jsamr** [comment]
Closing now, feel free to reopen after providing a reproducible example.
